// export const SERVICES = [
//   { id: 'custom-development', title: 'Custom Development', route: '/services/custom-development' },
//   { id: 'blockchain-development', title: 'Blockchain Development', route: '/services/blockchain-development' },
//   { id: 'ai-development', title: 'AI Development', route: '/services/ai-development' },
//   { id: 'smart-contract-development', title: 'Smart Contract Development', route: '/services/smart-contract-development' },
//   { id: 'smart-contract-audit', title: 'Smart Contract Audit', route: '/services/smart-contract-audit' },
//   { id: 'token-development', title: 'Token Development', route: '/services/token-development' },
//   { id: 'crypto-exchange-development', title: 'Crypto Exchange Development', route: '/services/crypto-exchange-development' },
//   { id: 'blockchain-consulting', title: 'Blockchain Consulting', route: '/services/blockchain-consulting' },
//   { id: 'defi-development', title: 'DeFi Development', route: '/services/defi-development' },
//   { id: 'nft-marketplace-development', title: 'NFT Marketplace Development', route: '/services/nft-marketplace-development' },
//   { id: 'dapp-development', title: 'DApp Development', route: '/services/dapp-development' },
//   { id: 'wallet-development', title: 'Wallet Development', route: '/services/wallet-development' },
// ];

 export const SERVICES = [
  {
    id: 'blockchain-development',
    title: 'Blockchain Development',
    label: 'Blockchain Development',
    route: '/services/blockchain-development',
    path: '/services/blockchain-development',
  },
  {
    id: 'ai-development',
    title: 'AI Development',
    label: 'AI Development',
    route: '/services/ai-development',
    path: '/services/ai-development',
  },
  {
    id: 'smart-contract-development',
    title: 'Smart Contract Development',
    label: 'Smart Contract Development',
    route: '/services/smart-contract-development',
    path: '/services/smart-contract-development',
  },
  {
    id: 'smart-contract-audit',
    title: 'Smart Contract Audit',
    label: 'Smart Contract Audit',
    route: '/services/smart-contract-audit',
    path: '/services/smart-contract-audit',
  },
  {
    id: 'token-development',
    title: 'Token Development',
    label: 'Token Development',
    route: '/services/token-development',
    path: '/services/token-development',
  },
  {
    id: 'crypto-exchange-development',
    title: 'Crypto Exchange Development',
    label: 'Crypto Exchange Development',
    route: '/services/crypto-exchange-development',
    path: '/services/crypto-exchange-development',
  },
  {
    id: 'defi-development',
    title: 'DeFi Development',
    label: 'DeFi Development',
    route: '/services/defi-development',
    path: '/services/defi-development',
  },
  {
    id: 'nft-marketplace-development',
    title: 'NFT Marketplace Development',
    label: 'NFT Marketplace Development',
    route: '/services/nft-marketplace-development',
    path: '/services/nft-marketplace-development',
  },
  {
    id: 'dapp-development',
    title: 'DApp Development',
    label: 'DApp Development',
    route: '/services/dapp-development',
    path: '/services/dapp-development',
  },
  {
    id: 'wallet-development',
    title: 'Wallet Development',
    label: 'Wallet Development',
    route: '/services/wallet-development',
    path: '/services/wallet-development',
  },
  {
    id: 'custom-development',
    title: 'Custom Blockchain Development',
    label: 'Custom Blockchain Development',
    route: '/services/custom-development',
    path: '/services/custom-development',
  },
  {
    id: 'blockchain-consulting',
    title: 'Consulting Services',
    label: 'Consulting Services',
    route: '/services/consulting',
    path: '/services/consulting',
  },
  {
    id: 'website-development',
    title: 'Website Development',
    label: 'Website Development',
    route: '/services/website-development',
    path: '/services/website-development',
  },
  {
    id: 'mobile-application-development',
    title: 'Mobile Application Development',
    label: 'Mobile Application Development',
    route: '/services/mobile-application-development',
    path: '/services/mobile-application-development',
  },
];

